In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Dataset loading

In [2]:
gwas_alzheimer = r"C:\Users\ext.andre.santos\Documents\Trabalho\datasets_PrivacyHumanGenomes\gwas-association_alzheimer.tsv"

alzheimer_df = (pd.read_csv(gwas_alzheimer, sep="\t"))#, header=None))

In [3]:
alzheimer_df

,DATE ADDED TO CATALOG,PUBMEDID,FIRST AUTHOR,DATE,JOURNAL,LINK,STUDY,DISEASE/TRAIT,INITIAL SAMPLE SIZE,REPLICATION SAMPLE SIZE,...,PVALUE_MLOG,P-VALUE (TEXT),OR or BETA,95% CI (TEXT),PLATFORM [SNPS PASSING QC],CNV,MAPPED_TRAIT,MAPPED_TRAIT_URI,STUDY ACCESSION,GENOTYPING TECHNOLOGY
0,2025-07-11,39023044,Ge YJ,2024-07-18,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/39023044,Genome-wide meta-analysis identifies ancestry-...,Early-onset Alzheimer's disease,"630 Chinese ancestry cases, 787 Chinese ancest...",NaN,...,5.522879,NaN,1.294050,[0.76-1.83] unit decrease,Illumina [7676018] (imputed),N,early-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_0022957,GCST90558102,Genome-wide genotyping array
1,2025-07-11,39023044,Ge YJ,2024-07-18,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/39023044,Genome-wide meta-analysis identifies ancestry-...,Early-onset Alzheimer's disease,"630 Chinese ancestry cases, 787 Chinese ancest...",NaN,...,6.397940,NaN,0.563058,[0.35-0.78] unit decrease,Illumina [7676018] (imputed),N,early-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_0022957,GCST90558102,Genome-wide genotyping array
2,2025-07-11,39023044,Ge YJ,2024-07-18,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/39023044,Genome-wide meta-analysis identifies ancestry-...,Early-onset Alzheimer's disease,"630 Chinese ancestry cases, 787 Chinese ancest...",NaN,...,5.698970,NaN,0.542028,[0.32-0.77] unit increase,Illumina [7676018] (imputed),N,early-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_0022957,GCST90558102,Genome-wide genotyping array
3,2025-07-11,39023044,Ge YJ,2024-07-18,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/39023044,Genome-wide meta-analysis identifies ancestry-...,Early-onset Alzheimer's disease,"630 Chinese ancestry cases, 787 Chinese ancest...",NaN,...,5.397940,NaN,0.539554,[0.31-0.77] unit decrease,Illumina [7676018] (imputed),N,early-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_0022957,GCST90558102,Genome-wide genotyping array
4,2025-07-11,39023044,Ge YJ,2024-07-18,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/39023044,Genome-wide meta-analysis identifies ancestry-...,Early-onset Alzheimer's disease,"630 Chinese ancestry cases, 787 Chinese ancest...",NaN,...,5.397940,NaN,0.594791,[0.34-0.85] unit increase,Illumina [7676018] (imputed),N,early-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_0022957,GCST90558102,Genome-wide genotyping array
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5677,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,8.698970,NaN,1.040000,[1.03-1.05],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array
5678,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,9.000000,NaN,1.280000,[1.18-1.39],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array
5679,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,7.301030,NaN,0.920000,[0.89-0.95],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array
5680,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,8.698970,NaN,0.930000,[0.91-0.95],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array
5681,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,9.301030,NaN,1.050000,[1.04-1.07],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array

In [4]:
alzheimer_df.columns

Index(['DATE ADDED TO CATALOG', 'PUBMEDID', 'FIRST AUTHOR', 'DATE', 'JOURNAL',
       'LINK', 'STUDY', 'DISEASE/TRAIT', 'INITIAL SAMPLE SIZE',
       'REPLICATION SAMPLE SIZE', 'REGION', 'CHR_ID', 'CHR_POS',
       'REPORTED GENE(S)', 'MAPPED_GENE', 'UPSTREAM_GENE_ID',
       'DOWNSTREAM_GENE_ID', 'SNP_GENE_IDS', 'UPSTREAM_GENE_DISTANCE',
       'DOWNSTREAM_GENE_DISTANCE', 'STRONGEST SNP-RISK ALLELE', 'SNPS',
       'MERGED', 'SNP_ID_CURRENT', 'CONTEXT', 'INTERGENIC',
       'RISK ALLELE FREQUENCY', 'P-VALUE', 'PVALUE_MLOG', 'P-VALUE (TEXT)',
       'OR or BETA', '95% CI (TEXT)', 'PLATFORM [SNPS PASSING QC]', 'CNV',
       'MAPPED_TRAIT', 'MAPPED_TRAIT_URI', 'STUDY ACCESSION',
       'GENOTYPING TECHNOLOGY'],
      dtype='object')

In [5]:
alzheimer_df["CHR_ID"].unique()

array(['7', '16', '11', '2', '14', '5', '17', '4', '8', '12', '19', '9',
       '1', '10', '18', '6', nan, '3', '22', '20', '13', '15', '21', 'X',
       '15 x 5', '5 x 15', '8;8;8', '1;1', '10;10;10'], dtype=object)

In [6]:
alzheimer_df["SNPS"]

0          rs757278
1        rs55889290
2       rs111785670
3        rs28531854
4         rs1980513
           ...
5677     rs13276936
5678    rs138799625
5679     rs58840546
5680    rs112131072
5681    rs149080927
Name: SNPS, Length: 5682, dtype: object

In [7]:
alzheimer_df["CONTEXT"].unique()

array(['intron_variant', 'intergenic_variant', nan, 'missense_variant',
       'TF_binding_site_variant', '3_prime_UTR_variant',
       'non_coding_transcript_exon_variant', 'regulatory_region_variant',
       'synonymous_variant', '5_prime_UTR_variant',
       'splice_region_variant', 'stop_gained',
       'splice_polypyrimidine_tract_variant', 'frameshift_variant',
       'inframe_insertion', 'intron_variant x synonymous_variant',
       'intron_variant x intron_variant',
       'intron_variant; 5_prime_UTR_variant; intron_variant',
       'intron_variant; non_coding_transcript_exon_variant',
       'intron_variant; intron_variant; intron_variant'], dtype=object)

In [8]:
alzheimer_df["INTERGENIC"].unique()

array([ 0.,  1., nan])

In [9]:
alzheimer_df["DISEASE/TRAIT"].unique()

array(["Early-onset Alzheimer's disease",
       "Late-onset Alzheimer's disease",
       'Late-onset Alzheimer’s disease in APOEe4 non-carriers',
       "Late-onset Alzheimer's disease (adjusted for APOE)",
       "Alzheimer's disease in hypertension-negative individuals",
       "Alzheimer's disease in hypertension", "Alzheimer's disease",
       "Alzheimer's disease (age of onset)",
       'Alzheimer disease and age of onset',
       "Alzheimer's disease (late onset)",
       "Alzheimer's disease (cognitive decline)",
       "Rapidly progressive Alzheimer's disease (typical) (case-control set 2)",
       "Rapidly progressive Alzheimer's disease (clinical) (case-control set 2)",
       "Rapidly progressive Alzheimer's disease (clinical vs typical) (case-control set 2)",
       "Rapidly progressive Alzheimer's disease (typical) (case-control set 1)",
       "Rapidly progressive Alzheimer's disease (clinical) (case-control set 1)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed) (case-control set 1)",
       "Rapidly progressive Alzheimer's disease (clinical vs typical) (case-control set 1)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed) (case-control set 3)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed vs typical) (case-control set 3)",
       "Rapidly progressive Alzheimer's disease (typical) (case-control set 3)",
       "Rapidly progressive Alzheimer's disease (clinical) (case-control set 3)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed) (case-control set 2)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed vs typical) (case-control set 2)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed vs typical) (case-control set 1)",
       "Rapidly progressive Alzheimer's disease (pathologically-confirmed vs clinical) (case-control set 1)",
       "Rapidly progressive Alzheimer's disease (clinical vs typical) (case-control set 3)",
       "Alzheimer's disease (survival time)", 'Alzheimer disease (MTAG)',
       "Alzheimer's disease (onset at age over 80)",
       "Alzheimer's disease (onset between ages 58 and 79)",
       "Alzheimer's disease or fasting glucose levels (pleiotropy)",
       "Alzheimer's disease or fasting insulin levels (pleiotropy)",
       "Alzheimer's disease or HDL levels (pleiotropy)",
       "Alzheimer's disease (MTAG)",
       "Alzheimer's disease or body fat percentage (pleiotropy)",
       "Alzheimer's disease or diastolic blood pressure (pleiotropy)",
       "Alzheimer's disease or systolic blood pressure (pleiotropy)",
       "Alzheimer's disease or waist-hip ratio (pleiotropy)",
       'Alzheimer’s disease polygenic risk score (upper quantile vs lower quantile)',
       "Alzheimer's disease or educational attainment (pleiotropy)",
       "Alzheimer's disease and Lewy body co-pathology",
       "Alzheimer's disease pathology",
       "Alzheimer's disease (age of onset) (adjusted for APOE e4 carrier status)",
       "Alzheimer's disease (age of onset) in APOE e4 non-carriers",
       "Dementia or Alzheimer's disease",
       "Vascular dementia or Alzheimer's disease",
       "Alzheimer's disease in APOE E4 homozygosity",
       "Alzheimer's disease in non-APOE e4 carriers",
       "Alzheimer's disease in APOE e4+ carriers",
       "Alzheimer's disease or family history of Alzheimer's disease",
       "Alzheimer's disease or small vessel stroke",
       "Entorhinal cortical thickness (Alzheimer's disease interaction)",
       "Entorhinal cortical volume (Alzheimer's disease interaction)",
       "Whole-brain volume (Alzheimer's disease interaction)",
       "Accelerated cognitive decline after conversion of mild cognitive impairment to Alzheimer's disease (Alzhiemer's diagnosis trajectory interaction)",
       "Alzheimer's disease biomarkers",
       'Brain structure (temporal lobe volume)',
       "Cerebrospinal fluid levels of Alzheimer's disease-related proteins",
       "Alzheimer's disease or gastroesophageal reflux disease",
       "Alzheimer's disease or peptic ulcer disease",
       "Alzheimer's disease or LDL levels (pleiotropy)",
       "Alzheimer's disease in APOE e4- carriers",
       "Alzheimer's disease, proxy Alzheimer's disease or related dementias",
       "Alzheimer's disease with no specific cognitive domain impairment",
       "Posterior cortical atrophy and Alzheimer's disease",
       "Total ventricular volume (Alzheimer's disease interaction)",
       "Psychosis and Alzheimer's disease",
       "Alzheimer's disease or related dementias (adjusted for APOE E4 dosage)",
       "Alzheimer's disease, proxy Alzheimer's disease or related dementias (adjusted for APOE E4 dosage)",
       "Alzheimer's disease or gastroesophageal reflux disease and/or peptic ulcer disease",
       "Alzheimer's disease (SNP x SNP interaction)",
       "Late-onset Alzheimer's disease in high risk polygenic risk score",
       "Alzheimer's disease with memory domain impairment",
       "Alzheimer's disease with language domain impairment",
       "Alzheimer's disease with visuospatial domain impairment",
       "Alzheimer's disease with multiple cognitive domain impairments",
       'Alzheimer’s disease and/or vascular dementia (clinical subgroup VaD+)',
       'Alzheimer’s disease (clinical subgroup AD+)',
       'Alzheimer’s disease (clinical subgroup AD++)',
       'Alzheimer’s disease (clinical subgroup AD+++)',
       'Alzheimer’s disease and/or vascular dementia (clinical subgroup VaD++)',
       "Alzheimer's disease (APOE e4 interaction)",
       "Logical memory (immediate recall) in Alzheimer's disease dementia",
       "Cerebrospinal AB1-42 levels in Alzheimer's disease dementia",
       "Cerebrospinal fluid t-tau levels in Alzheimer's disease dementia",
       "Logical memory (delayed recall) in Alzheimer's disease dementia",
       "Cerebrospinal fluid p-tau levels in Alzheimer's disease dementia",
       "Hippocampal volume in Alzheimer's disease dementia",
       'Cerebrospinal fluid clusterin levels in APOEe4- carriers',
       'Plasma amyloid beta 42 levels in Alzheimer disease',
       'Plasma neurofilament light levels in Alzheimer disease',
       'Plasma glial fibrillary acidic protein levels in Alzheimer disease',
       'Plasma p-tau181 levels in Alzheimer disease',
       'Plasma amyloid beta 42 to 40 ratio in Alzheimer disease',
       "Rate of cognitive decline in Alzheimer's disease",
       "Response to cholinesterase inhibitors in Alzheimer's disease",
       'Cerebral amyloid angiopathy in APOEe4 carrier Alzheimer’s disease',
       'Cerebral amyloid angiopathy in APOEe4 non-carrier Alzheimer’s disease',
       'Cerebral amyloid angiopathy x sex interaction in Alzheimer’s disease',
       'Cerebral amyloid angiopathy x APOEe4 status interaction in Alzheimer’s disease',
       'Cerebral amyloid angiopathy in Alzheimer’s disease',
       'Sphingomyeline (d43:1/d34:1) ratio in Alzheimer disease',
       "Alzheimer's disease (PheCode 290.11)",
       "Psychosis in Alzheimer's disease",
       "Alzheimer's disease (clinical and registry cases) (r-XCI inactivation)",
       "Alzheimer's disease or dementia (clinical, registry and proxy cases)  (r-XCI inactivation)",
       "Alzheimer's disease (clinical cases)  (r-XCI inactivation)",
       "Alzheimer's disease (clinical and registry cases) (e-XCI inactivation)"],
      dtype=object)

In [10]:
alzheimer_1_df = alzheimer_df.loc[alzheimer_df["CHR_ID"] == "1"]
alzheimer_1_df

,DATE ADDED TO CATALOG,PUBMEDID,FIRST AUTHOR,DATE,JOURNAL,LINK,STUDY,DISEASE/TRAIT,INITIAL SAMPLE SIZE,REPLICATION SAMPLE SIZE,...,PVALUE_MLOG,P-VALUE (TEXT),OR or BETA,95% CI (TEXT),PLATFORM [SNPS PASSING QC],CNV,MAPPED_TRAIT,MAPPED_TRAIT_URI,STUDY ACCESSION,GENOTYPING TECHNOLOGY
23,2025-07-11,39023044,Ge YJ,2024-07-18,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/39023044,Genome-wide meta-analysis identifies ancestry-...,Early-onset Alzheimer's disease,"630 Chinese ancestry cases, 787 Chinese ancest...",NaN,...,5.045757,NaN,0.389791,[0.22-0.56] unit decrease,Illumina [7676018] (imputed),N,early-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_0022957,GCST90558102,Genome-wide genotyping array
37,2017-03-24,27770636,Mez J,2016-10-20,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/27770636,"Two novel loci, COBL and SLC10A2, for Alzheime...",Late-onset Alzheimer's disease,"1,825 African American ancestry cases, 3,784 A...",NaN,...,5.221849,(liability model),0.090000,[0.051-0.129] unit decrease,NR [19725427] (imputed),N,late-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_1001870,GCST003815,Genome-wide genotyping array
43,2017-03-24,27770636,Mez J,2016-10-20,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/27770636,"Two novel loci, COBL and SLC10A2, for Alzheime...",Late-onset Alzheimer's disease,"1,825 African American ancestry cases, 3,784 A...",NaN,...,6.000000,(liability model),0.070000,[0.031-0.109] unit increase,NR [19725427] (imputed),N,late-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_1001870,GCST003815,Genome-wide genotyping array
78,2017-03-24,27770636,Mez J,2016-10-20,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/27770636,"Two novel loci, COBL and SLC10A2, for Alzheime...",Late-onset Alzheimer's disease,"1,825 African American ancestry cases, 3,784 A...",NaN,...,6.301030,(liability model),0.880000,[0.55-1.21] unit decrease,NR [19725427] (imputed),N,late-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_1001870,GCST003815,Genome-wide genotyping array
96,2017-03-24,27770636,Mez J,2016-10-20,Alzheimers Dement,www.ncbi.nlm.nih.gov/pubmed/27770636,"Two novel loci, COBL and SLC10A2, for Alzheime...",Late-onset Alzheimer's disease,"1,825 African American ancestry cases, 3,784 A...",NaN,...,5.154902,(liability model),0.440000,[0.24-0.64] unit decrease,NR [19725427] (imputed),N,late-onset Alzheimers disease,http://www.ebi.ac.uk/efo/EFO_1001870,GCST003815,Genome-wide genotyping array
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,2021-10-20,34112972,DeMichele-Sweet MAA,2021-06-10,Mol Psychiatry,www.ncbi.nlm.nih.gov/pubmed/34112972,Genome-wide association identifies the first r...,Psychosis in Alzheimer's disease,"4,551 European ancestry cases, 5,796 European ...",NaN,...,5.045757,NaN,1.210000,[1.11-1.31],Illumina [7105229] (imputed),N,psychotic symptoms,http://www.ebi.ac.uk/efo/EFO_0005940,GCST90020050,Genome-wide genotyping array
5551,2021-10-20,34112972,DeMichele-Sweet MAA,2021-06-10,Mol Psychiatry,www.ncbi.nlm.nih.gov/pubmed/34112972,Genome-wide association identifies the first r...,Psychosis in Alzheimer's disease,"4,551 European ancestry cases, 5,796 European ...",NaN,...,5.045757,NaN,1.440000,[1.23-1.69],Illumina [7105229] (imputed),N,psychotic symptoms,http://www.ebi.ac.uk/efo/EFO_0005940,GCST90020050,Genome-wide genotyping array
5594,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,45.154902,NaN,1.130000,[1.11-1.15],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array
5620,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,8.096910,NaN,1.380000,[1.24-1.54],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array
5675,2022-04-06,35379992,Bellenguez C,2022-04-04,Nat Genet,www.ncbi.nlm.nih.gov/pubmed/35379992,New insights into the genetic etiology of Alzh...,Alzheimer's disease,"39,106 European ancestry clinically diagnosed ...","25,392 cases, 276,086 controls",...,7.698970,NaN,1.040000,[1.03-1.06],"Affymetrix, Illumina [21101114] (imputed)",N,Alzheimer disease,http://purl.obolibrary.org/obo/MONDO_0004975,GCST90027158,Genome-wide genotyping array

In [11]:
alzheimer_1_df["CHR_POS"]

23      185343062
37      169617708
43      111350283
78      147483513
96       19693032
          ...
5550     57621274
5551    235155396
5594    207577223
5620    109345810
5675    161141573
Name: CHR_POS, Length: 287, dtype: object

#### Processing and density computation

In [12]:
cytoband_read = r"C:\Users\ext.andre.santos\Documents\Privacy_sens_human_genome\A_map_of_privacy-sensitivity_in_human_genomes-main\cytobands\cytobandFiltered_processed_str_dr_dg_gv_sorted.txt"
cb_df = pd.read_csv(cytoband_read, sep="\t")
cb_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,TandemRepeats_dens,STRs_dens,LTRs_dens,DRs_density,...,five_prime_UTRIntron_density,five_prime_UTRExon_density,three_prime_UTRs_density,three_prime_UTRIntron_density,three_prime_UTRExon_density,exons_density,SNP_density,Indel_density,Inserts_density,Deletes_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.087516,0.006384,0.084476,0.326328,...,0.005135,0.005529,0.026310,0.025853,0.000456,0.133749,0.022000,0.006463,0.001590,0.004900
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084077,0.013902,0.079223,0.281556,...,0.001761,0.001512,0.019776,0.019406,0.000370,0.060012,0.033405,0.008639,0.002013,0.006659
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056236,0.012909,0.051421,0.275410,...,0.002073,0.003586,0.025848,0.025715,0.000133,0.056062,0.030704,0.009019,0.002377,0.006688
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049082,0.013229,0.042217,0.404844,...,0.002070,0.001499,0.015875,0.015746,0.000129,0.034280,0.028061,0.009503,0.002497,0.007044
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.055881,0.011072,0.048928,0.404047,...,0.002176,0.002777,0.029553,0.028516,0.001037,0.066018,0.028159,0.008768,0.002322,0.006476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,chrY,12400000,17099999,q11.221,gpos50,4699999,0.036956,0.014211,0.029356,0.015158,...,0.000344,0.000583,0.002534,0.002459,0.000075,0.009953,0.000000,0.000000,0.000000,0.000000
858,chrY,17100000,19599999,q11.222,gneg,2499999,0.061662,0.015902,0.052790,0.012965,...,0.000338,0.000008,0.000937,0.000635,0.000302,0.033020,0.000000,0.000000,0.000000,0.000000
859,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082234,0.005789,0.078347,0.006441,...,0.000037,0.000503,0.002733,0.002733,0.000000,0.021283,0.000000,0.000000,0.000000,0.000000
860,chrY,23800000,26599999,q11.23,gneg,2799999,0.026278,0.009164,0.020721,0.001822,...,0.000345,0.000308,0.002016,0.001749,0.000267,0.022278,0.000000,0.000000,0.000000,0.000000
861,chrY,26600000,57227414,q12,gvar,30627414,0.005530,0.001643,0.004251,0.000594,...,0.000000,0.000005,0.000094,0.000094,0.000000,0.000460,0.000000,0.000000,0.000000,0.000000

In [13]:
def calc_AlzheimersSNPDensity(cytobands_df, alzheimer_df, col_name = "alzheimer_SNP_density"):
    densities = []
    for chrom in cytobands_df["Chromossome"].unique():             
        print("searching cytobands in chromossome: ", chrom)
        chr_cytobands = cytobands_df.loc[cytobands_df['Chromossome'] == chrom]
        chr_size = chr_cytobands["Last_index"][chr_cytobands.index[-1]]+1
        cytobands_alzheimers = np.zeros((chr_size), dtype=int)
        chr_alzheimers = alzheimer_df.loc[alzheimer_df["CHR_ID"] == chrom.split("r")[1]]
        #percorrer o dataset pelas vulnerabilidades no cromossoma e anotar na lista np.zeroes
        for row in chr_alzheimers.index:
            cytobands_alzheimers[int(chr_alzheimers["CHR_POS"][row])]+=1
        #Calculo da densidade para cada cytoband
        for cytoband in chr_cytobands.index:
            cytoband_array = cytobands_alzheimers[int(chr_cytobands["First_index"][cytoband]):int(chr_cytobands["Last_index"][cytoband])+1]
            dr_length = np.count_nonzero(cytoband_array)
            cytoband_length = chr_cytobands["Size"][cytoband]
            density = dr_length/cytoband_length
            densities.append(round(density, 10))
        
    cytobands_df.insert(len(cytobands_df.columns), col_name, densities, True)

In [14]:
def writetxt(txt_path, df):
    with open(txt_path, 'w') as f:
        df_string = df.to_string(header=False, index=False)
        f.write(df_string)
        f.close

def writeNewtxt(file_path, df):
    """Writes a pandas dataframe into txt, columns separated by tabs ("\t")
    """
    f = open(file_path, 'w')
    str_cols = ""
    for col in df.columns[:-1]:
        str_cols += col + "\t"
    str_cols += df.columns.values[-1]+ "\n"
    f.write(str(str_cols))
    for row in df.values:
        str_row = ""
        for col in row[:-1]:
            str_row += str(col) + "\t"
        str_row += str(row[-1])+ "\n"
        f.write(str_row)
    f.close

### Running density computations

In [15]:
calc_AlzheimersSNPDensity(cb_df, alzheimer_df, col_name = "alzheimer_SNP_density")

searching cytobands in chromossome:  chr1
searching cytobands in chromossome:  chr2
searching cytobands in chromossome:  chr3
searching cytobands in chromossome:  chr4
searching cytobands in chromossome:  chr5
searching cytobands in chromossome:  chr6
searching cytobands in chromossome:  chr7
searching cytobands in chromossome:  chr8
searching cytobands in chromossome:  chr9
searching cytobands in chromossome:  chr10
searching cytobands in chromossome:  chr11
searching cytobands in chromossome:  chr12
searching cytobands in chromossome:  chr13
searching cytobands in chromossome:  chr14
searching cytobands in chromossome:  chr15
searching cytobands in chromossome:  chr16
searching cytobands in chromossome:  chr17
searching cytobands in chromossome:  chr18
searching cytobands in chromossome:  chr19
searching cytobands in chromossome:  chr20
searching cytobands in chromossome:  chr21
searching cytobands in chromossome:  chr22
searching cytobands in chromossome:  chrX
searching cytobands in chromossome:  chrY

In [26]:
cb_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,TandemRepeats_dens,STRs_dens,LTRs_dens,DRs_density,...,five_prime_UTRExon_density,three_prime_UTRs_density,three_prime_UTRIntron_density,three_prime_UTRExon_density,exons_density,SNP_density,Indel_density,Inserts_density,Deletes_density,alzheimer_SNP_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.087516,0.006384,0.084476,0.326328,...,0.005529,0.026310,0.025853,0.000456,0.133749,0.022000,0.006463,0.001590,0.004900,1.304300e-06
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084077,0.013902,0.079223,0.281556,...,0.001512,0.019776,0.019406,0.000370,0.060012,0.033405,0.008639,0.002013,0.006659,0.000000e+00
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056236,0.012909,0.051421,0.275410,...,0.003586,0.025848,0.025715,0.000133,0.056062,0.030704,0.009019,0.002377,0.006688,1.666700e-06
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049082,0.013229,0.042217,0.404844,...,0.001499,0.015875,0.015746,0.000129,0.034280,0.028061,0.009503,0.002497,0.007044,5.000000e-07
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.055881,0.011072,0.048928,0.404047,...,0.002777,0.029553,0.028516,0.001037,0.066018,0.028159,0.008768,0.002322,0.006476,4.705900e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,chrY,12400000,17099999,q11.221,gpos50,4699999,0.036956,0.014211,0.029356,0.015158,...,0.000583,0.002534,0.002459,0.000075,0.009953,0.000000,0.000000,0.000000,0.000000,0.000000e+00
858,chrY,17100000,19599999,q11.222,gneg,2499999,0.061662,0.015902,0.052790,0.012965,...,0.000008,0.000937,0.000635,0.000302,0.033020,0.000000,0.000000,0.000000,0.000000,0.000000e+00
859,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082234,0.005789,0.078347,0.006441,...,0.000503,0.002733,0.002733,0.000000,0.021283,0.000000,0.000000,0.000000,0.000000,0.000000e+00
860,chrY,23800000,26599999,q11.23,gneg,2799999,0.026278,0.009164,0.020721,0.001822,...,0.000308,0.002016,0.001749,0.000267,0.022278,0.000000,0.000000,0.000000,0.000000,0.000000e+00
861,chrY,26600000,57227414,q12,gvar,30627414,0.005530,0.001643,0.004251,0.000594,...,0.000005,0.000094,0.000094,0.000000,0.000460,0.000000,0.000000,0.000000,0.000000,0.000000e+00

In [27]:
cytoband_write = r"C:\Users\ext.andre.santos\Documents\Privacy_sens_human_genome\A_map_of_privacy-sensitivity_in_human_genomes-main\cytobands\cytobandFiltered_processed_all_sorted.txt"
writeNewtxt(cytoband_write, cb_df)

## Metric Studies

In [28]:
cytoband_read1 = r"C:\Users\ext.andre.santos\Documents\Privacy_sens_human_genome\A_map_of_privacy-sensitivity_in_human_genomes-main\cytobands\cytobandFiltered_processed_all_sorted.txt"
cb_df1 = pd.read_csv(cytoband_read1, sep="\t")
cb_df1

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,TandemRepeats_dens,STRs_dens,LTRs_dens,DRs_density,...,five_prime_UTRExon_density,three_prime_UTRs_density,three_prime_UTRIntron_density,three_prime_UTRExon_density,exons_density,SNP_density,Indel_density,Inserts_density,Deletes_density,alzheimer_SNP_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.087516,0.006384,0.084476,0.326328,...,0.005529,0.026310,0.025853,0.000456,0.133749,0.022000,0.006463,0.001590,0.004900,1.304300e-06
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084077,0.013902,0.079223,0.281556,...,0.001512,0.019776,0.019406,0.000370,0.060012,0.033405,0.008639,0.002013,0.006659,0.000000e+00
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056236,0.012909,0.051421,0.275410,...,0.003586,0.025848,0.025715,0.000133,0.056062,0.030704,0.009019,0.002377,0.006688,1.666700e-06
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049082,0.013229,0.042217,0.404844,...,0.001499,0.015875,0.015746,0.000129,0.034280,0.028061,0.009503,0.002497,0.007044,5.000000e-07
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.055881,0.011072,0.048928,0.404047,...,0.002777,0.029553,0.028516,0.001037,0.066018,0.028159,0.008768,0.002322,0.006476,4.705900e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,chrY,12400000,17099999,q11.221,gpos50,4699999,0.036956,0.014211,0.029356,0.015158,...,0.000583,0.002534,0.002459,0.000075,0.009953,0.000000,0.000000,0.000000,0.000000,0.000000e+00
858,chrY,17100000,19599999,q11.222,gneg,2499999,0.061662,0.015902,0.052790,0.012965,...,0.000008,0.000937,0.000635,0.000302,0.033020,0.000000,0.000000,0.000000,0.000000,0.000000e+00
859,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082234,0.005789,0.078347,0.006441,...,0.000503,0.002733,0.002733,0.000000,0.021283,0.000000,0.000000,0.000000,0.000000,0.000000e+00
860,chrY,23800000,26599999,q11.23,gneg,2799999,0.026278,0.009164,0.020721,0.001822,...,0.000308,0.002016,0.001749,0.000267,0.022278,0.000000,0.000000,0.000000,0.000000,0.000000e+00
861,chrY,26600000,57227414,q12,gvar,30627414,0.005530,0.001643,0.004251,0.000594,...,0.000005,0.000094,0.000094,0.000000,0.000460,0.000000,0.000000,0.000000,0.000000,0.000000e+00

In [30]:
def test_Alzheimersvalues(cytobands_df, col_name = "Alzheimer_metric"):
    alzheimer_densities = []
    metric_values = []
    for cytoband in cytobands_df.index:
        SNP_dens = cytobands_df["SNP_density"][cytoband]
        Alzheimer_snp_dens = cytobands_df["alzheimer_SNP_density"][cytoband]
        Alzheimer_dens = Alzheimer_snp_dens/SNP_dens
        alzheimer_densities.append(round(Alzheimer_dens, 10))
        #metric = 0.20 * SNP_dens + Alzheimer_dens * SNP_dens * 1000
        metric = 0.20 * SNP_dens + Alzheimer_snp_dens * 1000
        #metric = 0.20 * SNP_dens + Alzheimer_snp_dens * 1000 * SNP_dens 
        metric_values.append(round(metric, 10))

    cytobands_df.insert(len(cytobands_df.columns), "Alzheimer_dens", alzheimer_densities, True)
    cytobands_df.insert(len(cytobands_df.columns), col_name, metric_values, True)

In [31]:
test_Alzheimersvalues(cb_df1)

C:\Users\ext.andre.santos\AppData\Local\Temp\ipykernel_28052\161402556.py:7: RuntimeWarning: invalid value encountered in scalar divide
  Alzheimer_dens = Alzheimer_snp_dens/SNP_dens
C:\Users\ext.andre.santos\AppData\Local\Temp\ipykernel_28052\161402556.py:7: RuntimeWarning: divide by zero encountered in scalar divide
  Alzheimer_dens = Alzheimer_snp_dens/SNP_dens

In [32]:
cb_df1

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,TandemRepeats_dens,STRs_dens,LTRs_dens,DRs_density,...,three_prime_UTRIntron_density,three_prime_UTRExon_density,exons_density,SNP_density,Indel_density,Inserts_density,Deletes_density,alzheimer_SNP_density,Alzheimer_dens,Alzheimer_metric
0,chr1,0,2299999,p36.33,gneg,2299999,0.087516,0.006384,0.084476,0.326328,...,0.025853,0.000456,0.133749,0.022000,0.006463,0.001590,0.004900,1.304300e-06,0.000059,0.005704
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084077,0.013902,0.079223,0.281556,...,0.019406,0.000370,0.060012,0.033405,0.008639,0.002013,0.006659,0.000000e+00,0.000000,0.006681
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056236,0.012909,0.051421,0.275410,...,0.025715,0.000133,0.056062,0.030704,0.009019,0.002377,0.006688,1.666700e-06,0.000054,0.007808
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049082,0.013229,0.042217,0.404844,...,0.015746,0.000129,0.034280,0.028061,0.009503,0.002497,0.007044,5.000000e-07,0.000018,0.006112
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.055881,0.011072,0.048928,0.404047,...,0.028516,0.001037,0.066018,0.028159,0.008768,0.002322,0.006476,4.705900e-06,0.000167,0.010338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,chrY,12400000,17099999,q11.221,gpos50,4699999,0.036956,0.014211,0.029356,0.015158,...,0.002459,0.000075,0.009953,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
858,chrY,17100000,19599999,q11.222,gneg,2499999,0.061662,0.015902,0.052790,0.012965,...,0.000635,0.000302,0.033020,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
859,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082234,0.005789,0.078347,0.006441,...,0.002733,0.000000,0.021283,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
860,chrY,23800000,26599999,q11.23,gneg,2799999,0.026278,0.009164,0.020721,0.001822,...,0.001749,0.000267,0.022278,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000
861,chrY,26600000,57227414,q12,gvar,30627414,0.005530,0.001643,0.004251,0.000594,...,0.000094,0.000000,0.000460,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000

In [33]:
cb_df1["Alzheimer_metric"]

0      0.005704
1      0.006681
2      0.007808
3      0.006112
4      0.010338
         ...
857    0.000000
858    0.000000
859    0.000000
860    0.000000
861    0.000000
Name: Alzheimer_metric, Length: 862, dtype: float64

In [34]:
max(cb_df1["Alzheimer_metric"])

0.17352928

In [35]:
min(cb_df1["Alzheimer_metric"])

0.0

In [36]:
cytoband_write1 = r"C:\Users\ext.andre.santos\Documents\Privacy_sens_human_genome\A_map_of_privacy-sensitivity_in_human_genomes-main\cytobands\cytobandComplete_sorted.txt"
writeNewtxt(cytoband_write1, cb_df1)